### ISSUE TITLE
Button text cropped

### ISSUE THREAD

**Issue by RonSkons** [newawe/AceEditor#1]

**Comment by RonSkons** [comment]
![](http://i.imgur.com/9jdbxcZ.jpg)
The save and open button text appears to be cropped on Safari.

**Comment by haylinmoore** [comment]
Hmm

**Comment by haylinmoore** [comment]
Thanks for reporting. I will do some testing? May you please provide you safari version?

**Comment by RonSkons** [comment]
Mobile Safari 9.1 on an iPhone 4S.

**Comment by haylinmoore** [comment]
Oh xD. Phones are not supported ATM and anyway who codes on a phone

**Comment by RonSkons** [comment]
Oh lol. People who don't have access to a computer? Anyways it seems to work well on my Mac, except downloads don't quite work. It opens the data url, but instead of forcing a download, it just renders it.

**Comment by haylinmoore** [comment]
Yeah I can't make it download ATM if you know how that would be great
